### ISSUE TITLE
ValueError: Length of values does not match length of index

### ISSUE THREAD

**Issue by segelmichael** [BioNinja/GSEApy#19]
Hello! I just cannot figure out how to make it so that the expected len of the index matches the actual length of the index. Every time I run gseapy.call I get the same result that the two are not equivalent!

Thoughts on the matter?

**Comment by BioNinja** [comment]
Usually, it's the problem of your expression table. Could you try the gseapy-v0.7.1, and told me the commands your have used in command.txt file? In
 Plus, could you please tell me your expression table structures? Like how many columns your have? @segelmichael

**Comment by segelmichael** [comment]
BioNinja, thank you for your response! I have the version you mentioned! I am importing a pandas dataframe of RNA-sequencing FPKM values. I have tried even just trimming down the len() of the file to 10 genes across the four samples and it still gives me the same error. I assume that the columns are the sample names and the index is the genes? 

Here is the code:
```
glia = pd.read_csv('dat2.csv', index_col=0, header=0) #import dataframe where the index is in col = 0 and the smaple names are in row = 0
opc = glia[[1,2,4,5]] #i isolate a subset of the data
sample_names = ['A', 'B', 'B', 'A'] #like in GSEA java applet I do pairwise comparisons
call_results = gs.call(data=opc,gene_sets='KEGG_2016', cls=sample_names) #I think this is all I would need? 
```

**Comment by BioNinja** [comment]
@segelmichael  Do you mean that sample are in rows and gene nameas are in coloumns?

An expression table are like this:

![txt_format_snapshot](https://cloud.githubusercontent.com/assets/5889336/19307061/1f24c3f2-90ab-11e6-90d8-dd5ea0ad6d7b.gif)


You could see gseapy examples for dataframe structures at: http://pythonhosted.org/gseapy/gseapy_example.html

**Comment by segelmichael** [comment]
BioNinja, 

thank you very much! That solved the problem. The index cannot be the list of genes. There cannot be a pandas dataframe index. Any gene list must be column zero! 

Thanks for being so on top of it!

**Comment by BioNinja** [comment]
I'm glad that it worked for you. I'm sorry I did not make a clear statement in the document file. I will leave this issue opened for someone suffering the same problem.

**Comment by linehammer** [comment]
The ValueError: Length of values does not match [length of index](http://net-informations.com/ds/err/length.htm) raised because the previous columns you have added in the DataFrame are not the same length as the most recent one you have attempted to add in the DataFrame. So, you need make sure that the length of the array you are assign to a new column is equal to the length of the dataframe .

The simple solution is that you first convert the list/array to a pandas Series , and then when you do assignment, missing index in the Series will be filled with NaN values .

```
df = pd.DataFrame({'X': [1,2,3,4]})
df['Y'] = pd.Series([3,4])
```
