### ISSUE TITLE
How could I run ssGSEA with your module?

### ISSUE THREAD

**Issue by carlotarp** [BioNinja/GSEApy#20]
Hi, 

If I run your implementation of gsea, from the pre-rank step, per each sample that I have it would be the same than running ssGSEA?

Thank you

**Comment by BioNinja** [comment]
I'm sorry @carlotarp , ``prerank`` module is not the same with single sample GSEA. I did not implement ssGSEA in gseapy now.

**Comment by avkitex** [comment]
It would be great!

**Comment by EmanuelGoncalves** [comment]
Yes, please. This feature would be great.

**Comment by BioNinja** [comment]
Hi, guys, @carlotarp @avkitex @EmanuelGoncalves ,  
      single sample GSEA module has beed added to GSEApy. Install the lastest PR and run in the shell
```bash
    # add other options if your like, e.g. min_size=10
    $ gseapy single --data expression.txt --gmt gene_sets.gmt
```
or run in the python interactive console
```python
    #python code
    from gseapy.gsea import SingleSampleGSEA
    ss = SingleSampleGSEA(data="expression.txt", gene_sets= "gene_sets.gmt")
    ss.run()
```

Input file requirements:
1.  the format of "expression.txt",  It's exactly the same with the  ``prerank`` module's **rnk** file.  
In other words, the first column should be gene name, the second column should be absolute expression values
2. all the genes in the  genes_set(gene_sets.gmt), should be found in your gene expression  file(expression.txt).

I don't have time to write the full docs now. Sorry
