### ISSUE TITLE
TypeERROR

### ISSUE THREAD

**Issue by kopardev** [BioNinja/GSEApy#21]
With my genelist I am getting this error:
TypeError: sequence item 109: expected str instance, float found

gseapy prerank -r `ls D*rnk` -g /Users/kopardevn/Downloads/h.all.v6.0.symbols.gmt -o prerank_test_report_2
Traceback (most recent call last):
  File "/Users/kopardevn/anaconda/bin/gseapy", line 11, in <module>
    sys.exit(main())
  File "/Users/kopardevn/anaconda/lib/python3.6/site-packages/gseapy/__main__.py", line 43, in main
    args.ascending, args.figsize, args.format, args.graph, args.seed)
  File "/Users/kopardevn/anaconda/lib/python3.6/site-packages/gseapy/gsea.py", line 300, in prerank
    rdict['genes'] = ",".join(dat2.ix[ind,'gene_name'].tolist())
TypeError: sequence item 109: expected str instance, float found

h.all.v6.0.symbols.gmt has been downloaded from http://software.broadinstitute.org/gsea/downloads.jsp
 and the genelist is 

[D.rnk.txt](https://github.com/BioNinja/gseapy/files/943142/D.rnk.txt)

**Comment by BioNinja** [comment]
I made some format changes in the version 0.7.7. That's why your gene list is failed(My test gene list runs ok). 

You could install gseapy-v0.7.8 using pip, which fixes your problem. Thanks. @kopardev
