### ISSUE TITLE
Properly saving replot figures 

### ISSUE THREAD

**Issue by kuod** [BioNinja/GSEApy#22]
Hi,

I've noticed that when running `gseapy replot` the output folder does not contain any output files. I believe this is because of the save command on line 77 of `gsea.py`. 

The problem is the extra period after the first forward slash, which makes the files appear as invisible on my OS X filesystem. 

I have updated my local version like so:
`fig.savefig('{a}/{b}.gsea.replot.{c}'.format(a=outdir, b=enrich_term, c=format),`
and now see produced files.

**Comment by BioNinja** [comment]
Thank you for reporting the bug. Yes, there's a extra period in the source code
