### ISSUE TITLE
gseapy.enrichr crashes on non-default gene set

### ISSUE THREAD

**Issue by ilyasoifer** [BioNinja/GSEApy#25]
Example (python 2.7)
import gseapy 
l = ['SCARA3', 'LOC100044683', 'CMBL', 'CLIC6', 'IL13RA1', 'TACSTD2', 'DKKL1', 'CSF1',
     'SYNPO2L', 'TINAGL1', 'PTX3', 'BGN', 'HERC1', 'EFNA1', 'CIB2', 'PMP22', 'TMEM173']

enrichr = gseapy.enrichr(gene_list=l, description='pathway', gene_sets='GO_Biological_Process_2017', outdir='test', cutoff=0.2)

Crashes

NameError                                 Traceback (most recent call last)
<ipython-input-504-04c2bf8f93f8> in <module>()
      3      'SYNPO2L', 'TINAGL1', 'PTX3', 'BGN', 'HERC1', 'EFNA1', 'CIB2', 'PMP22', 'TMEM173']
      4 
----> 5 enrichr = gseapy.enrichr(gene_list=l, description='pathway', gene_sets='GO_Biological_Process_2017', outdir='test', cutoff=0.2)
      6 
      7 # or a txt file path.

/usr/lib/python2.7/site-packages/gseapy/enrichr.pyc in enrichr(gene_list, gene_sets, description, outdir, cutoff, format, figsize, top_term, no_plot, verbose)
    150     enr = Enrichr(gene_list, gene_sets, description, outdir,
    151                   cutoff, format, figsize, top_term, no_plot, verbose)
--> 152     enr.run()
    153 
    154     return enr

/usr/lib/python2.7/site-packages/gseapy/enrichr.pyc in run(self)
     55             enrichr_library = DEFAULT_LIBRARY
     56         else:
---> 57             enrichr_library = get_library_name()
     58             if gene_set not in enrichr_library:
     59                 sys.stderr.write("%s is not a enrichr library name\n"%gene_set)

NameError: global name 'get_library_name' is not defined

**Comment by BioNinja** [comment]
@ilyasoifer , get_library_name was missing, it has been fixed now. install the lastest PR:
```bash
     pip install git+git://github.com/BioNinja/gseapy.git#egg=gseapy
```
then run again. Thanks
