### ISSUE TITLE
ssGSEA FDR q value > 1

### ISSUE THREAD

**Issue by alejandro-jimenezsanchez** [BioNinja/GSEApy#26]
Hi,

I ran ssGSEA with GSEApy unsing the MutSigDB hallmarks gene set and everything looks OK, except that for some of the gene sets I get FDR q values > 1.

Is this a bug?

Thanks,
Alejandro

**Comment by BioNinja** [comment]
@alejandro-jimenezsanchez ,which version did you use? 
try to install the latest version of GSEApy(v0.8.3), which fixed this issue.

**Comment by alejandro-jimenezsanchez** [comment]
I see, I had version 0.8.1. Thanks!!! And thanks for creating such a nice package :)!
