### ISSUE TITLE
multiprocessing issue

### ISSUE THREAD

**Issue by iseekwonderful** [BioNinja/GSEApy#28]
Python version: `3.5`
GSEApy version `0.8.3`
Platform: `macOS 10.12.5`

When I follow the example from [EXAMPLE](http://pythonhosted.org/gseapy/gseapy_example.html) of the session `GSEA`, I got the result like this:

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>es</th>
      <th>nes</th>
      <th>pval</th>
      <th>fdr</th>
      <th>gene_set_size</th>
      <th>matched_size</th>
      <th>genes</th>
    </tr>
    <tr>
      <th>Term</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Cytokine-cytokine receptor interaction_Homo sapiens_hsa04060</th>
      <td>0.229069</td>
      <td>1.556522</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>265</td>
      <td>18</td>
      <td>IL10RB,VEGFC,CSF1,TNFSF12,LTBR,CXCL10,TNFRSF1A...</td>
    </tr>
    <tr>
      <th>Ras signaling pathway_Homo sapiens_hsa04014</th>
      <td>0.332033</td>
      <td>1.141144</td>
      <td>0.002004</td>
      <td>0.002003</td>
      <td>227</td>
      <td>18</td>
      <td>ETS1,GNG13,RRAS,VEGFC,GNB4,CSF1,SOS2,FGF17,PDG...</td>
    </tr>
    <tr>
      <th>Rap1 signaling pathway_Homo sapiens_hsa04015</th>
      <td>-0.285975</td>
      <td>-1.621806</td>
      <td>0.000000</td>
      <td>0.005941</td>
      <td>211</td>
      <td>19</td>
      <td>RRAS,VEGFC,CSF1,FGF17,PDGFRB,FGF4,PDGFC,SIPA1L...</td>
    </tr>
    <tr>
      <th>MAPK signaling pathway_Homo sapiens_hsa04010</th>
      <td>-0.392928</td>
      <td>-1.037983</td>
      <td>0.500000</td>
      <td>0.010396</td>
      <td>255</td>
      <td>18</td>
      <td>GADD45B,RRAS,SOS2,FGF17,PPP3CC,TNFRSF1A,PDGFRB...</td>
    </tr>
    <tr>
      <th>HTLV-I infection_Homo sapiens_hsa05166</th>
      <td>-0.249752</td>
      <td>-0.899335</td>
      <td>0.666667</td>
      <td>0.996040</td>
      <td>258</td>
      <td>19</td>
      <td>FZD2,ETS1,STAT5B,RRAS,LTBR,PPP3CC,TNFRSF1A,EGR...</td>
    </tr>
    <tr>
      <th>PI3K-Akt signaling pathway_Homo sapiens_hsa04151</th>
      <td>0.182245</td>
      <td>0.668758</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>341</td>
      <td>22</td>
      <td>GNG13,VEGFC,GNB4,CSF1,SOS2,FGF17,THBS4,PDGFRB,...</td>
    </tr>
    <tr>
      <th>Pathways in cancer_Homo sapiens_hsa05200</th>
      <td>0.201838</td>
      <td>0.573342</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>397</td>
      <td>27</td>
      <td>FZD2,ETS1,STAT5B,GNG13,VEGFC,GNB4,SOS2,FGF17,E...</td>
    </tr>
  </tbody>
</table>

It is strange that the P-value is either 0 or 1, after investigate the source, it seems the null distribution broken.

the part of value of the esnull:

```
[-0.5277168069182326, -0.3607821392991908, -0.27070554833780985, 0.14716709004244327, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, -0.19182208447985646, ....]
```
the value after index 4 are identical, which lead to a odd normal distribution.

And after trace of the identical value, I find the odd value is caused by the multiprocessing.Pool.

```
    if permutation_type == "phenotype":
        l2 = list(classes)
        dat2 = dat.copy()
        #multi-threading for rankings.
        rank_nulls=[]
        pool_rnkn = Pool(processes=processes) 

 
        for i in range(n):
            rs.shuffle(l2) 
            rank_nulls.append(pool_rnkn.apply_async(_rnknull, args=(dat2, method, 
                                                                  phenoPos, phenoNeg,
                                                                  l2, ascending)))
        pool_rnkn.close()
        pool_rnkn.join()
```
In fact, the 1000 times RandomState.shuffle is done after the multiprocessing.Pool close. so the classes vector live in the memory of `pool_rnkn` keep the reference of the last generated `l2`.

After copy the shuffle classes vector every time by:

```
for i in range(n):
            rs.shuffle(l2) 
            l3 = deepcopy(l2)
            rank_nulls.append(pool_rnkn.apply_async(_rnknull, args=(dat2, method, 
                                                                  phenoPos, phenoNeg,
                                                                  l3, ascending)))
```

Then the module calculates the correct p-value.

I am not sure if this issue only occur in my system, but seem several methods using multiprocessing.Pool may suffers this issue. And I hope this will be fixed soon.

Thanks~
Sheep

**Comment by BioNinja** [comment]
Sorry for replying late. Yes, you are right @iseekwonderful , the multiprocessing Pool use the same randomstate, leading to the final bug. This is unexpected when multi-cores are applied, and we don't want it. With some testing, I recaptured this issue on Windows a few times, too.

Thank you very much for pointing this critical bug out and make GSEApy better! 

-Zhuoqing

**Comment by iseekwonderful** [comment]
Could you please upgrade gseapy to 0.8.4 at pypi?

**Comment by BioNinja** [comment]
sure, but I need additional testing for other improvement. 0.8.4 will land soon.
