### ISSUE TITLE
when running GSEA on multiple gene sets which are ploted?

### ISSUE THREAD

**Issue by carlotarp** [BioNinja/GSEApy#34]
Hi, 

I am trying to figure out which gene sets are selected for the plotting of the enrichment score after running a GSEA pre-ranked for 836 gene sets. I am running it as the 3. Prerank example here
http://pythonhosted.org/gseapy/gseapy_example.html  

I cannot figure out which is the criteria for the plotting. Besides, could I force some how to see the plot of a particular enrichment performed? 
Thank you

**Comment by BioNinja** [comment]
Hi, @carlotarp , GSEA enrichment plots the top 20 gene_sets ranked by by fdr. You could check the .csv file for detail in your output dirs.

**Comment by carlotarp** [comment]
Thank you!
