### ISSUE TITLE
Heatmap scale bar

### ISSUE THREAD

**Issue by AlicePsyche** [BioNinja/GSEApy#35]
Hi, 

Sorry for the interruption, it seems a stupid question but I did not find the answer in the documentation. 

After I run GSEA, I got the heatmap like the below one: [KD, KD, control, control]. I initially thought this indicated that these genes were repressed in my KD samples. 
![image](https://user-images.githubusercontent.com/13633282/31940298-37df8980-b883-11e7-913b-fd13576e1603.png)

But when I checked these genes in my input files and did scatter plot I am confused... It is indeed that these genes show down-regulated tendency in KD samples( X axis: KD, Y axis: control) but not as significant as they did in previous heatmap. Could you please explain what the heatmap value stands for? Why the scale is -1~1? 

I used normalized read counts as input. The scatter plot is log2(counts + 1) 
![image](https://user-images.githubusercontent.com/13633282/31940389-97dfecc6-b883-11e7-8864-f09f345a44c7.png)

Thanks for your help in advance!

**Comment by BioNinja** [comment]
for heatmap visualization, data is scaled by standard normalization, that's to said, for each data point x, the normalized values = (x - row_means)/row_standard_deviation.
