### ISSUE TITLE
NaNs in ssGSEA NES

### ISSUE THREAD

**Issue by alejandro-jimenezsanchez** [BioNinja/GSEApy#37]
Hi,

I have run ssGSEA using gseapy, the ES values I get are OK, but when I look at the NES values in some cases I get a NaN. I checked the corresponding ES values and they are not 0. For example in one case I have an ES == 327.7 and the NES == NaN. And this doesn't seem to relate to the geneset, because for the same geneset other samples have an ES and a numerical NES as expected.

Is this a bug?

Happy to provide some sample data if required.
Best,
Alejandro

**Comment by BioNinja** [comment]
@alejandro-jimenezsanchez , could you update gseapy to the latest version(0.8.10)? The latest one generate two new output file for es and nes, which fixed the issues you might have.   
find your results in these two file:
   - samples.raw.es.txt: enrichment score for all samples
   - samples.normalized.es.txt: normalized enrichment score (nes) for all samples

Another question is, How many samples do you have?  If you have only one sample input, these two files will not be seen (because nes could not be calculated).

For short, for older versions(<0.8.10) of gseapy.ssgsea use random permutation procedure to calculate nes, pval, fdr(which GSEA did the same thing). The latest version still do these calculation, but give additional two output file, and this is what you needed. 

You could see the release notes here: https://github.com/BioNinja/GSEApy/releases

**Comment by BioNinja** [comment]
0.9.0 has been released, close now

**Comment by alejandro-jimenezsanchez** [comment]
@BioNinja I'm now using version 0.9.0 and there are still some NaNs on the NES column, but none in the ES column. Reading at GSEA documentation they say [here](https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/FAQ#Where_are_the_GSEA_statistics_.28ES.2C_NES.2C_FDR.2C_FWER.2C_nominal_p_value.29_described.3F):

> What does it mean for a gene set to have NES and nominal p-values of NaN (also shown as blanks)?
> When adjusting for variation in gene set size, we normalize permuted ES(S, pi) and the observed ES(S) for a given S, separately rescaling the positive and negative scores by dividing by the mean of the ES(S, pi) to yield NES(S, pi) and NES(S). However, when the scores of the corresponding sign are absent, the mean ES(S, pi) = 0, and the division by zero will result in NaN values both for the NES(S, pi) and NES(S) as well as for the nominal p-values that follow from these calculations. The easiest way to overcome this issue would be to increase number of permutations. If this does not help, we recommend further exploring reasons for this bias. For example, it could be caused by a large difference in the number of samples of each phenotype class. For further details, please consult the GSEA PNAS 2005 paper, sections "Multiple Hypothesis Testing" in the "Mathematical Description of Methods" and the "Supporting Text" Appendix.
> 

I am using 1000 permutations... and right now I would prefer not to increase them since I'm using my laptop for this at the moment.

On a side note, when I compare the ES to the NES I see the following [correlation](https://drive.google.com/file/d/1TnLyv1EnWHbHWPoBzcWgt2zneDZCvP5N/view?usp=sharing). For some reason negative score correlations vary much more than positive score ones, is this expected?

Thanks for your help,

**Comment by BioNinja** [comment]
Would you mind send me your input data for reproducing the bugs?

**Comment by alejandro-jimenezsanchez** [comment]
Sure, please find it attached.
[OVCTp_log2exp_data.txt](https://github.com/BioNinja/GSEApy/files/1584862/OVCTp_log2exp_data.txt)

**Comment by BioNinja** [comment]
Thanks, @alejandro-jimenezsanchez , 
* for v0.9.0, it takes too much memory to run ``ssgsea``. Install 0.9.1 instead, which I've just released.
* I don't have idea how to fixed the problem you had, now. But I recommend you not to use nes calculated from random permutation procedure. use **samples.normalized.es.txt** instead.

I will look into that later when I have more time.

**Comment by alejandro-jimenezsanchez** [comment]
Thanks for pointing me to those files agains @BioNinja , that would make things easier! I just checked and the NES and ES of those files correlate perfectly. Thanks!

**Comment by BioNinja** [comment]
@alejandro-jimenezsanchez , Glad to help. You could turn off random permutation stats by setting permuation_num=0. This will speed up calculation.

I think I should make some docs for best practice of  ``ssgsea``

**Comment by BioNinja** [comment]
latest PR only calculate Enrichment Score and NES default (permutation_num =0). 

close now
