### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by Francesco1993** [BioNinja/GSEApy#39]
Hello BioNinja,
First of all thank you for your work! I'm a bio-informatics student and I'm trying to use your tool, however when I try to launch it gives me a memory error; this is a screen shot from my notebook.

![istantanea_2018-01-03_16-32-50](https://user-images.githubusercontent.com/28860592/34531508-d49a1558-f0b2-11e7-8d5e-ee469cd0aa26.png)

The dataframe that I'm currently using has shape (9002, 4). Indeed I'm using jupyter notebook with anaconda environment and python 3.6.3. The version of gseapy is 0.9.2. 

This is the code that I'm using:
gs_res = gp.gsea(data = final_df_gsea_cleaned, gene_sets = 'KEGG_2016',
                 cls = ['a', 'b', 'b', 'b'], outdir = './Data/gsea_report_bis')

Moreover I receive a warning from the program because I'm currently using negative values because I standardized (standard scaler of sklearn) my dataframe but running the same code with a dataframe without negative values ends up in the same failure. 

It is a problem related to the implementation or related to a wrong use? Because it is all the day that I'm trying to launch it but I fail every time. If you need any more details about the error please ask me.

Thank you!
Francesco

**Comment by BioNinja** [comment]
It's a problem to the tools itself. you could use v0.8.11 for now, but needs a lot of time to run @Francesco1993

**Comment by BioNinja** [comment]
@Francesco1993 , could you install the latest PR? this problem is fixed by dropping big ndarry computation.

install it by:

    pip install git+git://github.com/BioNinja/gseapy.git#egg=gseapy

**Comment by Francesco1993** [comment]
@BioNinja, I did as you said but I end up in the same result. These are some screens.
Requirement screen:
![istantanea_2018-01-04_10-05-23](https://user-images.githubusercontent.com/28860592/34556557-0c58f282-f137-11e7-850d-f3103f9b6f59.png)
Memory Error screen:
![istantanea_2018-01-04_10-04-46](https://user-images.githubusercontent.com/28860592/34556577-20ec203e-f137-11e7-95ab-7ea09ce89d58.png)
Thank you.

**Comment by BioNinja** [comment]
@Francesco1993 , have you restart your kernel and run? You could check gseapy version first if it's a fixed version. 
    if gseapy.__version__ == 0.9.3, then your issues will be gone

**Comment by Francesco1993** [comment]
I'm sorry, my version is still 0.9.2 although I updated it. Wrt kernel I rebooted laptop. I will try to update via Anaconda...

**Comment by Francesco1993** [comment]
I managed to install version 0.9.3. Thank you @BioNinja!
