### ISSUE TITLE
Use Requests library

### ISSUE THREAD

**Issue by cthoyt** [BioNinja/GSEApy#41]
I have a good feeling that the python2/3 switching can be made much easier with the `requests` library. 

https://github.com/BioNinja/GSEApy/blob/033b7b8361437847bffdb4be82d621472ee12b65/gseapy/parser.py#L154-L165

This could become:

```python
response = requests.get('http://amp.pharm.mssm.edu/Enrichr/geneSetLibrary?mode=meta')
gmt_data = response.json()
```
And this already takes care of python2/3 abstraction :) I'd be happy to submit a PR!

**Comment by cthoyt** [comment]
Edit: It looks like I'm going blind, because you've already done this and that was commented specifically as old code 😅

**Comment by BioNinja** [comment]
Thanks for you contribution.  I should have deleted the old code to make API more clear. We could improve other parts if you'd like to contribute.
